### ISSUE TITLE
Autoload WordPress core classes

### ISSUE THREAD

**Issue by szepeviktor** [pablo-pacheco/wp-namespace-autoloader#1]
@pablo-sg-pacheco This is my first try on autoloading WordPress core: https://github.com/szepeviktor/wordpress-autoloaded

It uses [Composer](https://packagist.org/packages/szepeviktor/wordpress-autoloaded) and is basically a shell script.

What do you think?

**Comment by pablo-sg-pacheco** [comment]
Hi,

Hum, it seems interesting, but what is the purpose?
I'm just asking because there are some libraries that already do that, for example:
https://github.com/johnpbloch/wordpress-core-installer

**Comment by szepeviktor** [comment]
> there are some libraries that already do that, for example:

Excuse me but no :( 

John's package "only" fetches WordPress core as a package, but it is untouched: it still does unconditional class loading, all classes are loaded all the time.

wordpress-autoloaded removes require statements from the core and does class autoloading: only necessary classes are loaded.

How would you make it clear in my readme??

_BTW you could use johnpbloch/wordpress in wordpress-autoloaded instead of the zip_

**Comment by pablo-sg-pacheco** [comment]
Cool!
I'll try it later.

Maybe if you try to explain the difference between other libraries and yours will be enough, just like you did to me, and a small example of how to use it, even though I suppose it should work like this

```
"require": {
	"szepeviktor/wordpress-autoloaded": "dev-master"
}
```

**Comment by szepeviktor** [comment]
Thank you very much. This is badly missing.

When I wrote "This is a boilerplate..." in the readme I thought people will think about the same thing as I.

You should not require this package as this is a boilerplate, a starting point for a WordPress installation: `git clone https://github.com/szepeviktor/wordpress-autoloaded.git` then `composer install` Of course you need a theme, plugins and configuration and database.

**Comment by pablo-sg-pacheco** [comment]
No problem :)
I noticed you improved the readme. Much better now.

Is it possible to update all the plugins/themes and wordpress using `composer update `?

**Comment by szepeviktor** [comment]
Of course! See https://wpackagist.org/ and johnpbloch/wordpress

**Comment by pablo-sg-pacheco** [comment]
Great :)
Let me know if you notice anything
